spring.application.name=unidz-portal-api

# Database Platform Routing
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unidz_portal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:engine_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:VaultSecurePassword2026}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Engine Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Security & CORS Constraints
server.port=8080